Repository Team-Ezel/VOZA-Backend-v1, pull requests merged in 2023-08, with the labels that each got.

#2 Get kakao user info
  build.gradle
  src/main/java/com/ezel/voza/domain/kakao/presentation/controller/KakaoController.java
  src/main/java/com/ezel/voza/domain/kakao/presentation/dto/response/KakaoAccount.java
  src/main/java/com/ezel/voza/domain/kakao/presentation/dto/response/KakaoTokenResponse.java
  src/main/java/com/ezel/voza/domain/kakao/presentation/dto/response/KakaoUserInfoResponse.java
  src/main/java/com/ezel/voza/domain/kakao/presentation/dto/response/Profile.java
  src/main/java/com/ezel/voza/domain/kakao/service/GetKakaoTokenService.java
  src/main/java/com/ezel/voza/domain/kakao/service/GetKakaoUserInfoService.java
  src/main/java/com/ezel/voza/global/config/WebClientConfig.java
  src/main/java/com/ezel/voza/global/security/config/SecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :one: Priority: High, :sparkler: Feature

#4 exception
  src/main/java/com/ezel/voza/global/error/BasicException.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
  src/main/java/com/ezel/voza/global/error/ErrorMessage.java
  src/main/java/com/ezel/voza/global/error/handler/GlobalExceptionHandler.java
Labels: :one: Priority: High, :sparkler: Feature

#5 Feat/kakao logout
  src/main/java/com/ezel/voza/domain/kakao/entity/KakaoToken.java
  src/main/java/com/ezel/voza/domain/kakao/presentation/controller/KakaoController.java
  src/main/java/com/ezel/voza/domain/kakao/presentation/dto/response/KakaoLogoutUserIdResponse.java
  src/main/java/com/ezel/voza/domain/kakao/repository/KakaoTokenRepository.java
  src/main/java/com/ezel/voza/domain/kakao/service/GetKakaoUserInfoService.java
  src/main/java/com/ezel/voza/domain/kakao/service/KakaoLogoutService.java
Labels: :two: Priority: Medium, :sparkler: Feature

#7 Feat/user signup
  src/main/java/com/ezel/voza/VozaApplication.java
  src/main/java/com/ezel/voza/domain/kakao/entity/KakaoToken.java
  src/main/java/com/ezel/voza/domain/kakao/service/GetKakaoUserInfoService.java
  src/main/java/com/ezel/voza/domain/user/entity/User.java
  src/main/java/com/ezel/voza/domain/user/entity/enums/Banned.java
  src/main/java/com/ezel/voza/domain/user/entity/enums/Role.java
  src/main/java/com/ezel/voza/domain/user/presentation/dto/request/SignUpRequest.java
  src/main/java/com/ezel/voza/domain/user/repository/UserRepository.java
  src/main/java/com/ezel/voza/domain/user/service/UserSignupService.java
  src/main/java/com/ezel/voza/domain/user/service/impl/UserSignUpServiceImpl.java
Labels: :one: Priority: High, ⚡️Simple, :sparkler: Feature

#8 게시판 생성 기능
  src/main/java/com/ezel/voza/domain/board/entity/Board.java
  src/main/java/com/ezel/voza/domain/board/entity/enums/BoardType.java
  src/main/java/com/ezel/voza/domain/board/presentation/BoardController.java
  src/main/java/com/ezel/voza/domain/board/presentation/dto/request/CreateBoardRequest.java
  src/main/java/com/ezel/voza/domain/board/repository/BoardRepository.java
  src/main/java/com/ezel/voza/domain/board/service/CreateBoardService.java
  src/main/java/com/ezel/voza/domain/board/service/impl/CreateBoardServiceImpl.java
Labels: :two: Priority: Medium, :sparkler: Feature

#12 Jwt 관련 파일 작성
  src/main/java/com/ezel/voza/VozaApplication.java
  src/main/java/com/ezel/voza/domain/user/entity/enums/Role.java
  src/main/java/com/ezel/voza/domain/user/repository/UserRepository.java
  src/main/java/com/ezel/voza/global/filter/JwtRequestFilter.java
  src/main/java/com/ezel/voza/global/security/auth/AuthDetails.java
  src/main/java/com/ezel/voza/global/security/auth/AuthDetailsService.java
  src/main/java/com/ezel/voza/global/security/config/SecurityConfig.java
  src/main/java/com/ezel/voza/global/security/exception/TokenExpiredException.java
  src/main/java/com/ezel/voza/global/security/exception/TokenNotVaildException.java
  src/main/java/com/ezel/voza/global/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/ezel/voza/global/security/handler/CustomAuthenticationEntryPointHandler.java
  src/main/java/com/ezel/voza/global/security/jwt/TokenProvider.java
  src/main/java/com/ezel/voza/global/security/jwt/properties/JwtProperties.java
  src/main/java/com/ezel/voza/global/security/jwt/properties/TokenTimeProperties.java
Labels: :one: Priority: High, :sparkler: Feature

#15 Feat/board-list
  src/main/java/com/ezel/voza/domain/board/presentation/BoardController.java
  src/main/java/com/ezel/voza/domain/board/presentation/dto/response/BoardResponse.java
  src/main/java/com/ezel/voza/domain/board/presentation/dto/response/ListBoardResponse.java
  src/main/java/com/ezel/voza/domain/board/service/ListBoardService.java
  src/main/java/com/ezel/voza/domain/board/service/impl/CreateBoardServiceImpl.java
  src/main/java/com/ezel/voza/domain/board/service/impl/ListBoardServiceImpl.java
Labels: :two: Priority: Medium, ⚡️Simple, :sparkler: Feature
