Repository Team-Ezel/VOZA-Backend-v1, pull requests merged in 2023-09, with the labels that each got.

#17 Feat/board-detail
  src/main/java/com/ezel/voza/domain/board/presentation/BoardController.java
  src/main/java/com/ezel/voza/domain/board/presentation/dto/response/DetailBoardResponse.java
  src/main/java/com/ezel/voza/domain/board/service/GetBoardDetailService.java
  src/main/java/com/ezel/voza/domain/board/service/impl/GetBoardDetailServiceImpl.java
Labels: :two: Priority: Medium, :sparkler: Feature

#20 Feat/group create
  src/main/java/com/ezel/voza/domain/group/entity/Group.java
  src/main/java/com/ezel/voza/domain/group/presentation/GroupController.java
  src/main/java/com/ezel/voza/domain/group/presentation/dto/request/CreateGroupRequest.java
  src/main/java/com/ezel/voza/domain/group/repository/GroupRepository.java
  src/main/java/com/ezel/voza/domain/group/service/CreateGroupService.java
  src/main/java/com/ezel/voza/domain/group/service/impl/CreateGroupServiceImpl.java
Labels: :one: Priority: High, :sparkler: Feature

#24 Feat/hotfix kakao exception
  src/main/java/com/ezel/voza/domain/kakao/service/GetKakaoUserInfoService.java
  src/main/java/com/ezel/voza/domain/user/repository/UserRepository.java
Labels: :bug: Bug, :zero: Priority: Critical

#22 Feat/delete-board
  src/main/java/com/ezel/voza/domain/board/presentation/BoardController.java
  src/main/java/com/ezel/voza/domain/board/service/DeleteBoardService.java
  src/main/java/com/ezel/voza/domain/board/service/impl/DeleteBoardServiceImpl.java
Labels: :two: Priority: Medium, :sparkler: Feature

#26 #25 Group Table명 변경
  src/main/java/com/ezel/voza/domain/group/entity/Group.java
Labels: :bug: Bug, :zero: Priority: Critical, ⚡️Simple

#28 Feat/hotfix method name
  src/main/java/com/ezel/voza/domain/kakao/service/GetKakaoUserInfoService.java
  src/main/java/com/ezel/voza/domain/user/repository/UserRepository.java
Labels: :bug: Bug, :zero: Priority: Critical, ⚡️Simple

#30 Feat/group create invite code
  src/main/java/com/ezel/voza/domain/group/entity/GroupInvite.java
  src/main/java/com/ezel/voza/domain/group/exception/GroupNotFoundException.java
  src/main/java/com/ezel/voza/domain/group/exception/NotGroupLeaderException.java
  src/main/java/com/ezel/voza/domain/group/presentation/GroupController.java
  src/main/java/com/ezel/voza/domain/group/repository/GroupInviteRepository.java
  src/main/java/com/ezel/voza/domain/group/service/CreateGroupInviteCode.java
  src/main/java/com/ezel/voza/domain/group/service/impl/CreateGroupInviteCodeImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
Labels: :one: Priority: High, :sparkler: Feature

#33 Feat/kakao code refactoring
  src/main/java/com/ezel/voza/domain/group/entity/GroupInvite.java
  src/main/java/com/ezel/voza/domain/kakao/service/GetKakaoUserInfoService.java
Labels: :bug: Bug, :one: Priority: High, :recycle: Refactoring

#35 Feat/hotfix entity error
  src/main/java/com/ezel/voza/domain/group/entity/Group.java
  src/main/java/com/ezel/voza/domain/group/presentation/dto/request/CreateGroupRequest.java
  src/main/java/com/ezel/voza/domain/user/entity/User.java
  src/main/java/com/ezel/voza/global/security/auth/AuthDetailsService.java
  src/main/java/com/ezel/voza/global/security/config/SecurityConfig.java
  src/main/java/com/ezel/voza/global/util/UserUtil.java
Labels: :bug: Bug, :zero: Priority: Critical, :recycle: Refactoring

#36 Feat/vote create
  src/main/java/com/ezel/voza/domain/vote/entity/Vote.java
  src/main/java/com/ezel/voza/domain/vote/entity/VoteOption.java
  src/main/java/com/ezel/voza/domain/vote/presentation/dto/VoteController.java
  src/main/java/com/ezel/voza/domain/vote/presentation/dto/request/CreateVoteRequest.java
  src/main/java/com/ezel/voza/domain/vote/repository/VoteRepository.java
  src/main/java/com/ezel/voza/domain/vote/service/CreateVoteService.java
  src/main/java/com/ezel/voza/domain/vote/service/impl/CreateVoteServiceImpl.java
  src/main/java/com/ezel/voza/global/util/GroupUtil.java
Labels: :two: Priority: Medium, ⚡️Simple, :sparkler: Feature

#37 Feat/vote list
  src/main/java/com/ezel/voza/domain/vote/presentation/dto/VoteController.java
  src/main/java/com/ezel/voza/domain/vote/presentation/dto/response/ListVoteResponse.java
  src/main/java/com/ezel/voza/domain/vote/presentation/dto/response/VoteResponse.java
  src/main/java/com/ezel/voza/domain/vote/repository/VoteRepository.java
  src/main/java/com/ezel/voza/domain/vote/service/ListVoteService.java
  src/main/java/com/ezel/voza/domain/vote/service/impl/ListVoteServiceImpl.java
Labels: :two: Priority: Medium, ⚡️Simple, :sparkler: Feature

#39 Feat/user into gruop
  src/main/java/com/ezel/voza/domain/group/entity/Group.java
  src/main/java/com/ezel/voza/domain/group/entity/GroupInvite.java
  src/main/java/com/ezel/voza/domain/group/exception/AlreadyExistGroupException.java
  src/main/java/com/ezel/voza/domain/group/exception/MisMatchInviteCodeException.java
  src/main/java/com/ezel/voza/domain/group/presentation/GroupController.java
  src/main/java/com/ezel/voza/domain/group/presentation/dto/request/EnterGroupRequest.java
  src/main/java/com/ezel/voza/domain/group/repository/GroupRepository.java
  src/main/java/com/ezel/voza/domain/group/service/CreateGroupInviteCode.java
  src/main/java/com/ezel/voza/domain/group/service/EnterGroupService.java
  src/main/java/com/ezel/voza/domain/group/service/impl/CreateGroupInviteCodeImpl.java
  src/main/java/com/ezel/voza/domain/group/service/impl/CreateGroupServiceImpl.java
  src/main/java/com/ezel/voza/domain/group/service/impl/EnterGroupServiceImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
Labels: :one: Priority: High, :sparkler: Feature, :recycle: Refactoring

#40 Feat/vote delete
  src/main/java/com/ezel/voza/domain/vote/exception/VoteAuthorMismatchException.java
  src/main/java/com/ezel/voza/domain/vote/exception/VoteNotFoundException.java
  src/main/java/com/ezel/voza/domain/vote/presentation/VoteController.java
  src/main/java/com/ezel/voza/domain/vote/service/CreateVoteService.java
  src/main/java/com/ezel/voza/domain/vote/service/DeleteVoteService.java
  src/main/java/com/ezel/voza/domain/vote/service/ListVoteService.java
  src/main/java/com/ezel/voza/domain/vote/service/impl/CreateVoteServiceImpl.java
  src/main/java/com/ezel/voza/domain/vote/service/impl/DeleteVoteServiceImpl.java
  src/main/java/com/ezel/voza/domain/vote/service/impl/ListVoteServiceImpl.java
  src/main/java/com/ezel/voza/global/util/GroupUtil.java
  src/main/java/com/ezel/voza/global/util/VoteUtil.java
Labels: :two: Priority: Medium, ⚡️Simple, :sparkler: Feature

#42 Feat/out group
  src/main/java/com/ezel/voza/domain/group/entity/Group.java
  src/main/java/com/ezel/voza/domain/group/exception/LeaderNotOutGroupException.java
  src/main/java/com/ezel/voza/domain/group/exception/NotExistGroupException.java
  src/main/java/com/ezel/voza/domain/group/presentation/GroupController.java
  src/main/java/com/ezel/voza/domain/group/service/OutGroupService.java
  src/main/java/com/ezel/voza/domain/group/service/impl/OutGroupServiceImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
Labels: :one: Priority: High, :sparkler: Feature

#43 Feat/vote detail
  src/main/java/com/ezel/voza/domain/vote/entity/VoteOption.java
  src/main/java/com/ezel/voza/domain/vote/presentation/VoteController.java
  src/main/java/com/ezel/voza/domain/vote/presentation/dto/response/DetailVoteResponse.java
  src/main/java/com/ezel/voza/domain/vote/service/GetVoteDetailService.java
  src/main/java/com/ezel/voza/domain/vote/service/impl/GetVoteDetailServiceImpl.java
Labels: :two: Priority: Medium, ⚡️Simple, :sparkler: Feature

#44 Feat/vote count up
  src/main/java/com/ezel/voza/domain/vote/entity/VoteOption.java
  src/main/java/com/ezel/voza/domain/vote/exception/VoteOptionMismatchException.java
  src/main/java/com/ezel/voza/domain/vote/presentation/VoteController.java
  src/main/java/com/ezel/voza/domain/vote/presentation/dto/request/AddCountRequest.java
  src/main/java/com/ezel/voza/domain/vote/repository/VoteOptionRepository.java
  src/main/java/com/ezel/voza/domain/vote/service/AddCountService.java
  src/main/java/com/ezel/voza/domain/vote/service/impl/AddCountServiceImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
Labels: :two: Priority: Medium, ⚡️Simple, :sparkler: Feature

#47 Feat/get group list
  build.gradle
  src/main/generated/com/ezel/voza/domain/board/entity/QBoard.java
  src/main/generated/com/ezel/voza/domain/group/entity/QGroup.java
  src/main/generated/com/ezel/voza/domain/user/entity/QUser.java
  src/main/generated/com/ezel/voza/domain/vote/entity/QVote.java
  src/main/generated/com/ezel/voza/domain/vote/entity/QVoteOption.java
  src/main/java/com/ezel/voza/domain/group/presentation/GroupController.java
  src/main/java/com/ezel/voza/domain/group/presentation/dto/response/GroupListResponse.java
  src/main/java/com/ezel/voza/domain/group/presentation/dto/response/GroupResponse.java
  src/main/java/com/ezel/voza/domain/group/repository/GroupRepository.java
  src/main/java/com/ezel/voza/domain/group/service/GroupListService.java
  src/main/java/com/ezel/voza/domain/group/service/impl/MyGroupListServiceImpl.java
  src/main/java/com/ezel/voza/domain/group/service/impl/NotContainsGroupServiceImpl.java
  src/main/java/com/ezel/voza/global/querydsl/QueryDslConfig.java
Labels: :one: Priority: High, :sparkler: Feature

#48 feat/hofix-user-entity-error
  src/main/java/com/ezel/voza/domain/user/entity/User.java
Labels: :bug: Bug, :zero: Priority: Critical, ⚡️Simple

#50 Feat/group s3 image
  build.gradle
  src/main/generated/com/ezel/voza/domain/group/entity/QGroup.java
  src/main/generated/com/ezel/voza/global/entity/QBaseTimeEntity.java
  src/main/java/com/ezel/voza/domain/file/exception/FileUploadFailedException.java
  src/main/java/com/ezel/voza/domain/file/exception/InvalidFormatFileException.java
  src/main/java/com/ezel/voza/domain/file/exception/NotAllowedFileException.java
  src/main/java/com/ezel/voza/domain/file/service/SingleFileUploadService.java
  src/main/java/com/ezel/voza/domain/file/service/impl/SingleFileUploadServiceImpl.java
  src/main/java/com/ezel/voza/domain/group/entity/Group.java
  src/main/java/com/ezel/voza/domain/group/presentation/GroupController.java
  src/main/java/com/ezel/voza/domain/group/service/CreateGroupService.java
  src/main/java/com/ezel/voza/domain/group/service/impl/CreateGroupServiceImpl.java
  src/main/java/com/ezel/voza/global/aws/S3Config.java
  src/main/java/com/ezel/voza/global/entity/BaseTimeEntity.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
  src/main/resources/application.yml
Labels: :zero: Priority: Critical, :sparkler: Feature

#52 Feat/group detail
  src/main/java/com/ezel/voza/domain/group/presentation/GroupController.java
  src/main/java/com/ezel/voza/domain/group/presentation/dto/response/GroupDetailResponse.java
  src/main/java/com/ezel/voza/domain/group/service/GroupDetailService.java
  src/main/java/com/ezel/voza/domain/group/service/impl/CreateGroupServiceImpl.java
  src/main/java/com/ezel/voza/domain/group/service/impl/GroupDetailServiceImpl.java
Labels: :one: Priority: High, :sparkler: Feature

#54 Feat/vote remove duplicates
  src/main/java/com/ezel/voza/domain/vote/entity/VoteOption.java
  src/main/java/com/ezel/voza/domain/vote/exception/AlreadyVotedUserException.java
  src/main/java/com/ezel/voza/domain/vote/repository/VoteOptionRepository.java
  src/main/java/com/ezel/voza/domain/vote/service/impl/AddCountServiceImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
Labels: :two: Priority: Medium, ⚡️Simple, :sparkler: Feature

#56 #55 GroupResponse 수정
  src/main/java/com/ezel/voza/domain/group/presentation/dto/response/GroupResponse.java
Labels: :zero: Priority: Critical, ⚡️Simple

#58 hotfix duplicates
  src/main/java/com/ezel/voza/domain/vote/service/impl/AddCountServiceImpl.java
Labels: :zero: Priority: Critical, ⚡️Simple

#60 Feat/user profile
  src/main/java/com/ezel/voza/domain/user/presentation/UserController.java
  src/main/java/com/ezel/voza/domain/user/presentation/dto/response/ProfileResponse.java
  src/main/java/com/ezel/voza/domain/user/service/GetProfileService.java
  src/main/java/com/ezel/voza/domain/user/service/impl/GetProfileServiceImpl.java
  src/main/java/com/ezel/voza/global/security/config/SecurityConfig.java
Labels: :one: Priority: High, :sparkler: Feature

#62 Feat/hotfix vote option error
  src/main/generated/com/ezel/voza/domain/vote/entity/QVoteOption.java
  src/main/java/com/ezel/voza/domain/vote/entity/VoteOption.java
  src/main/java/com/ezel/voza/domain/vote/presentation/VoteController.java
Labels: :bug: Bug, :one: Priority: High, :recycle: Refactoring

#64 Feat/group list pagination
  src/main/java/com/ezel/voza/domain/group/presentation/GroupController.java
  src/main/java/com/ezel/voza/domain/group/service/OtherGroupListService.java
  src/main/java/com/ezel/voza/domain/group/service/impl/NotContainsGroupServiceImpl.java
Labels: :one: Priority: High, :sparkler: Feature

#66 Feat/create calender
  src/main/java/com/ezel/voza/domain/calender/entity/Calender.java
  src/main/java/com/ezel/voza/domain/calender/presentation/CalenderController.java
  src/main/java/com/ezel/voza/domain/calender/presentation/dto/request/CreateCalenderRequest.java
  src/main/java/com/ezel/voza/domain/calender/repository/CalenderRepository.java
  src/main/java/com/ezel/voza/domain/calender/service/CreateCalenderService.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/CreateCalenderServiceImpl.java
Labels: :one: Priority: High, :sparkler: Feature

#72 Feat/give admin access
  gradlew
  src/main/java/com/ezel/voza/domain/group/presentation/GroupController.java
  src/main/java/com/ezel/voza/domain/user/entity/User.java
  src/main/java/com/ezel/voza/domain/user/exception/YouNotAdminException.java
  src/main/java/com/ezel/voza/domain/user/presentation/AdminController.java
  src/main/java/com/ezel/voza/domain/user/service/GrantAdminService.java
  src/main/java/com/ezel/voza/domain/user/service/impl/GrantAdminServiceImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
  src/main/java/com/ezel/voza/global/security/config/SecurityConfig.java
Labels: :one: Priority: High, :sparkler: Feature

#71 Feat/delete calender
  src/main/java/com/ezel/voza/domain/calender/Exception/CalenderAuthorMismatchException.java
  src/main/java/com/ezel/voza/domain/calender/Exception/CalenderNotFoundException.java
  src/main/java/com/ezel/voza/domain/calender/presentation/CalenderController.java
  src/main/java/com/ezel/voza/domain/calender/service/DeleteCalenderService.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/DeleteCalenderServiceImpl.java
  src/main/java/com/ezel/voza/global/util/CalenderUtil.java
Labels: :two: Priority: Medium, :sparkler: Feature

#74 Feat/update calender
  src/main/java/com/ezel/voza/domain/calender/entity/Calender.java
  src/main/java/com/ezel/voza/domain/calender/presentation/CalenderController.java
  src/main/java/com/ezel/voza/domain/calender/presentation/dto/request/UpdateCalenderRequest.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/UpdateCalenderServiceImpl.java
  src/main/java/com/ezel/voza/domain/calender/service/UpdateCalenderService.java
Labels: :two: Priority: Medium, :sparkler: Feature

#78 Feat/calender month list
  src/main/generated/com/ezel/voza/domain/calender/entity/QCalender.java
  src/main/java/com/ezel/voza/domain/calender/entity/Calender.java
  src/main/java/com/ezel/voza/domain/calender/presentation/CalenderController.java
  src/main/java/com/ezel/voza/domain/calender/presentation/dto/request/GetDateRequest.java
  src/main/java/com/ezel/voza/domain/calender/presentation/dto/response/CalenderMonthListResponse.java
  src/main/java/com/ezel/voza/domain/calender/presentation/dto/response/CalenderMonthResponse.java
  src/main/java/com/ezel/voza/domain/calender/repository/CalenderRepository.java
  src/main/java/com/ezel/voza/domain/calender/service/CalenderMonthListService.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/CalenderMonthListServiceImpl.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/CreateCalenderServiceImpl.java
Labels: :two: Priority: Medium, :sparkler: Feature

#79 Feat/user ban
  src/main/generated/com/ezel/voza/domain/auth/entity/QBlackUser.java
  src/main/java/com/ezel/voza/domain/auth/entity/BlackUser.java
  src/main/java/com/ezel/voza/domain/auth/exception/YouBanException.java
  src/main/java/com/ezel/voza/domain/auth/repository/BlackUserRepository.java
  src/main/java/com/ezel/voza/domain/auth/service/impl/UserLoginServiceImpl.java
  src/main/java/com/ezel/voza/domain/user/entity/User.java
  src/main/java/com/ezel/voza/domain/user/presentation/AdminController.java
  src/main/java/com/ezel/voza/domain/user/service/UserBanService.java
  src/main/java/com/ezel/voza/domain/user/service/impl/UserBanServiceImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
Labels: :one: Priority: High, :sparkler: Feature

#81 Feat/user unban
  src/main/java/com/ezel/voza/domain/auth/repository/BlackUserRepository.java
  src/main/java/com/ezel/voza/domain/user/exception/NotBlackUserException.java
  src/main/java/com/ezel/voza/domain/user/presentation/AdminController.java
  src/main/java/com/ezel/voza/domain/user/service/UserUnBanService.java
  src/main/java/com/ezel/voza/domain/user/service/impl/UserUnBanServiceImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
Labels: :one: Priority: High, :sparkler: Feature

#83 Feat/admin group ban
  src/main/generated/com/ezel/voza/domain/group/entity/QGroup.java
  src/main/java/com/ezel/voza/domain/group/entity/Group.java
  src/main/java/com/ezel/voza/domain/group/exception/NotAllowedEnterBanGroupException.java
  src/main/java/com/ezel/voza/domain/group/service/impl/CreateGroupServiceImpl.java
  src/main/java/com/ezel/voza/domain/group/service/impl/EnterGroupServiceImpl.java
  src/main/java/com/ezel/voza/domain/user/exception/ExistBanGroupException.java
  src/main/java/com/ezel/voza/domain/user/presentation/AdminController.java
  src/main/java/com/ezel/voza/domain/user/service/StopGroupService.java
  src/main/java/com/ezel/voza/domain/user/service/impl/StopGroupServiceImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
Labels: :one: Priority: High, ⚡️Simple, :sparkler: Feature

#85 Feat/bot report send discord
  build.gradle
  src/main/java/com/ezel/voza/domain/report/entity/Report.java
  src/main/java/com/ezel/voza/domain/report/entity/enums/ReportType.java
  src/main/java/com/ezel/voza/domain/report/presentation/ReportController.java
  src/main/java/com/ezel/voza/domain/report/presentation/dto/request/CreateReportRequest.java
  src/main/java/com/ezel/voza/domain/report/repository/ReportRepository.java
  src/main/java/com/ezel/voza/domain/report/service/SendReportService.java
  src/main/java/com/ezel/voza/domain/report/service/impl/SendReportServiceImpl.java
  src/main/java/com/ezel/voza/global/security/config/SecurityConfig.java
  src/main/java/com/ezel/voza/global/webhook/config/WebHookConfig.java
  src/main/java/com/ezel/voza/global/webhook/util/BotUtil.java
  src/main/resources/application.yml
Labels: :one: Priority: High, :sparkler: Feature

#87 Feat/report detail
  src/main/generated/com/ezel/voza/domain/report/entity/QReport.java
  src/main/java/com/ezel/voza/domain/report/exception/NotFoundReportException.java
  src/main/java/com/ezel/voza/domain/report/presentation/ReportController.java
  src/main/java/com/ezel/voza/domain/report/presentation/dto/response/DetailReportResponse.java
  src/main/java/com/ezel/voza/domain/report/service/DetailReportService.java
  src/main/java/com/ezel/voza/domain/report/service/impl/DetailReportServiceImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
Labels: :one: Priority: High, :sparkler: Feature

#89 Feat/report resend
  build.gradle
  src/main/java/com/ezel/voza/domain/report/exception/FailedEmailSendException.java
  src/main/java/com/ezel/voza/domain/report/presentation/AdminReportController.java
  src/main/java/com/ezel/voza/domain/report/presentation/ReportController.java
  src/main/java/com/ezel/voza/domain/report/service/RespondReportService.java
  src/main/java/com/ezel/voza/domain/report/service/impl/RespondReportServiceImpl.java
  src/main/java/com/ezel/voza/domain/report/service/impl/SendReportServiceImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
  src/main/resources/application.yml
Labels: :one: Priority: High, ⚡️Simple, :sparkler: Feature

#91 Feat/calender day list
  src/main/generated/com/ezel/voza/domain/calender/entity/QCalender.java
  src/main/java/com/ezel/voza/domain/calender/entity/Calender.java
  src/main/java/com/ezel/voza/domain/calender/presentation/CalenderController.java
  src/main/java/com/ezel/voza/domain/calender/presentation/dto/request/CreateCalenderRequest.java
  src/main/java/com/ezel/voza/domain/calender/presentation/dto/request/UpdateCalenderRequest.java
  src/main/java/com/ezel/voza/domain/calender/presentation/dto/response/CalenderDayListResponse.java
  src/main/java/com/ezel/voza/domain/calender/presentation/dto/response/CalenderDayResponse.java
  src/main/java/com/ezel/voza/domain/calender/presentation/dto/response/CalenderMonthResponse.java
  src/main/java/com/ezel/voza/domain/calender/repository/CalenderRepository.java
  src/main/java/com/ezel/voza/domain/calender/service/CalenderDayListService.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/CalenderDayListServiceImpl.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/CreateCalenderServiceImpl.java
Labels: :one: Priority: High, :sparkler: Feature, :recycle: Refactoring

#96 Feat/report list
  src/main/java/com/ezel/voza/domain/report/presentation/AdminReportController.java
  src/main/java/com/ezel/voza/domain/report/presentation/dto/response/ListReportResponse.java
  src/main/java/com/ezel/voza/domain/report/presentation/dto/response/ReportResponse.java
  src/main/java/com/ezel/voza/domain/report/service/ListReportService.java
  src/main/java/com/ezel/voza/domain/report/service/impl/ListReportServiceImpl.java
Labels: :one: Priority: High, :sparkler: Feature

#93 Feat/calender detail
  src/main/java/com/ezel/voza/domain/calender/presentation/CalenderController.java
  src/main/java/com/ezel/voza/domain/calender/presentation/dto/response/CalenderDetailResponse.java
  src/main/java/com/ezel/voza/domain/calender/service/CalenderDetailService.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/CalenderDetailServiceImpl.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/DeleteCalenderServiceImpl.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/UpdateCalenderServiceImpl.java
  src/main/java/com/ezel/voza/global/util/CalenderUtil.java
Labels: :one: Priority: High, ⚡️Simple, :sparkler: Feature

#99 Feat/group member list
  src/main/java/com/ezel/voza/domain/member/presentation/MemberController.java
  src/main/java/com/ezel/voza/domain/member/presentation/response/MemberListResponse.java
  src/main/java/com/ezel/voza/domain/member/presentation/response/MemberResponse.java
  src/main/java/com/ezel/voza/domain/member/service/MemberListService.java
  src/main/java/com/ezel/voza/domain/member/service/impl/MemberListServiceImpl.java
Labels: :one: Priority: High, :sparkler: Feature

#101 Feat/refuse send
  src/main/java/com/ezel/voza/domain/report/presentation/AdminReportController.java
  src/main/java/com/ezel/voza/domain/report/presentation/dto/request/SendRefuseRequest.java
  src/main/java/com/ezel/voza/domain/report/service/RefuseReportService.java
  src/main/java/com/ezel/voza/domain/report/service/impl/RefuseReportServiceImpl.java
Labels: :one: Priority: High, :sparkler: Feature

#102 Feat/group entity security
  src/main/java/com/ezel/voza/domain/group/entity/Group.java
  src/main/java/com/ezel/voza/domain/group/exception/EnterOnlyCodeException.java
  src/main/java/com/ezel/voza/domain/group/exception/YouNotLeaderException.java
  src/main/java/com/ezel/voza/domain/group/presentation/GroupController.java
  src/main/java/com/ezel/voza/domain/group/service/EnterByCodeGroupService.java
  src/main/java/com/ezel/voza/domain/group/service/EnterGroupService.java
  src/main/java/com/ezel/voza/domain/group/service/SetGroupSecurityService.java
  src/main/java/com/ezel/voza/domain/group/service/impl/CreateGroupServiceImpl.java
  src/main/java/com/ezel/voza/domain/group/service/impl/EnterByCodeGroupServiceImpl.java
  src/main/java/com/ezel/voza/domain/group/service/impl/EnterGroupServiceImpl.java
  src/main/java/com/ezel/voza/domain/group/service/impl/SetGroupSecurityServiceImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
Labels: :zero: Priority: Critical, :sparkler: Feature, :recycle: Refactoring

#104 Feat/kick out member
  src/main/java/com/ezel/voza/domain/member/exception/NotManagerException.java
  src/main/java/com/ezel/voza/domain/member/presentation/MemberController.java
  src/main/java/com/ezel/voza/domain/member/service/KickOutMemberService.java
  src/main/java/com/ezel/voza/domain/member/service/impl/KickOutMemberServiceImpl.java
  src/main/java/com/ezel/voza/global/util/UserUtil.java
Labels: :two: Priority: Medium, :sparkler: Feature

#107 Feat/group recommanded
  src/main/generated/com/ezel/voza/domain/group/entity/QGroup.java
  src/main/java/com/ezel/voza/domain/group/presentation/GroupController.java
  src/main/java/com/ezel/voza/domain/group/service/GroupRecommendedService.java
  src/main/java/com/ezel/voza/domain/group/service/impl/GroupRecommendedServiceImpl.java
Labels: :one: Priority: High, :sparkler: Feature

#109 Feat/fix board
  src/main/generated/com/ezel/voza/domain/board/entity/QBoard.java
  src/main/java/com/ezel/voza/domain/board/entity/Board.java
  src/main/java/com/ezel/voza/domain/board/presentation/BoardController.java
  src/main/java/com/ezel/voza/domain/board/presentation/dto/response/BoardResponse.java
  src/main/java/com/ezel/voza/domain/board/presentation/dto/response/DetailBoardResponse.java
  src/main/java/com/ezel/voza/domain/board/repository/BoardRepository.java
  src/main/java/com/ezel/voza/domain/board/service/CreateBoardService.java
  src/main/java/com/ezel/voza/domain/board/service/DeleteBoardService.java
  src/main/java/com/ezel/voza/domain/board/service/GetBoardDetailService.java
  src/main/java/com/ezel/voza/domain/board/service/ListBoardService.java
  src/main/java/com/ezel/voza/domain/board/service/UpdateBoardService.java
  src/main/java/com/ezel/voza/domain/board/service/impl/CreateBoardServiceImpl.java
  src/main/java/com/ezel/voza/domain/board/service/impl/DeleteBoardServiceImpl.java
  src/main/java/com/ezel/voza/domain/board/service/impl/GetBoardDetailServiceImpl.java
  src/main/java/com/ezel/voza/domain/board/service/impl/ListBoardServiceImpl.java
  src/main/java/com/ezel/voza/domain/board/service/impl/UpdateBoardServiceImpl.java
Labels: :bug: Bug, :zero: Priority: Critical, :recycle: Refactoring

#113 Feat/chat socket
  build.gradle
  src/main/generated/com/ezel/voza/domain/chat/entity/QRoom.java
  src/main/generated/com/ezel/voza/domain/chat/entity/QRoom_LastChat.java
  src/main/java/com/ezel/voza/domain/chat/entity/Room.java
  src/main/java/com/ezel/voza/domain/chat/exception/ExistRoomException.java
  src/main/java/com/ezel/voza/domain/chat/presenation/MessageController.java
  src/main/java/com/ezel/voza/domain/chat/presenation/RoomController.java
  src/main/java/com/ezel/voza/domain/chat/presenation/dto/request/Message.java
  src/main/java/com/ezel/voza/domain/chat/repository/RoomRepository.java
  src/main/java/com/ezel/voza/domain/chat/service/ChatSaveService.java
  src/main/java/com/ezel/voza/domain/chat/service/CreateRoomService.java
  src/main/java/com/ezel/voza/domain/chat/service/impl/ChatSaveServiceImpl.java
  src/main/java/com/ezel/voza/domain/chat/service/impl/CreateRoomServiceImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
  src/main/java/com/ezel/voza/global/security/config/SecurityConfig.java
  src/main/java/com/ezel/voza/global/websocket/WebSocketConfig.java
  src/main/resources/application.yml
Labels: :one: Priority: High, :sparkler: Feature

#112 Feat/add file
  src/main/generated/com/ezel/voza/domain/board/entity/QBoard.java
  src/main/java/com/ezel/voza/domain/board/entity/Board.java
  src/main/java/com/ezel/voza/domain/board/service/impl/CreateBoardServiceImpl.java
  src/main/java/com/ezel/voza/domain/board/service/impl/GetBoardDetailServiceImpl.java
  src/main/java/com/ezel/voza/domain/file/presentation/FileController.java
  src/main/java/com/ezel/voza/domain/file/presentation/response/FileUploadResponse.java
  src/main/java/com/ezel/voza/domain/file/service/FileUploadService.java
  src/main/java/com/ezel/voza/domain/file/service/impl/FileUploadServiceImpl.java
  src/main/java/com/ezel/voza/global/security/config/SecurityConfig.java
Labels: :one: Priority: High, ⚡️Simple, :sparkler: Feature

#115 Feat/stomp error handle
  src/main/java/com/ezel/voza/domain/chat/entity/Room.java
  src/main/java/com/ezel/voza/domain/chat/service/impl/ChatSaveServiceImpl.java
  src/main/java/com/ezel/voza/global/security/config/SecurityConfig.java
  src/main/java/com/ezel/voza/global/websocket/config/WebSocketConfig.java
  src/main/java/com/ezel/voza/global/websocket/handler/SocketErrorHandler.java
Labels: :two: Priority: Medium, ⚡️Simple
