Repository Team-Ezel/VOZA-Backend-v1, pull requests merged in 2023-10, with the labels that each got.

#117 Feat/chat list
  src/main/generated/com/ezel/voza/domain/chat/entity/QRoom.java
  src/main/generated/com/ezel/voza/domain/chat/entity/QRoomChat.java
  src/main/java/com/ezel/voza/domain/chat/entity/Room.java
  src/main/java/com/ezel/voza/domain/chat/entity/RoomChat.java
  src/main/java/com/ezel/voza/domain/chat/presenation/RoomController.java
  src/main/java/com/ezel/voza/domain/chat/presenation/dto/response/ChatListResponse.java
  src/main/java/com/ezel/voza/domain/chat/presenation/dto/response/ChatResponse.java
  src/main/java/com/ezel/voza/domain/chat/repository/RoomChatRepository.java
  src/main/java/com/ezel/voza/domain/chat/service/FindAllChatService.java
  src/main/java/com/ezel/voza/domain/chat/service/impl/ChatSaveServiceImpl.java
  src/main/java/com/ezel/voza/domain/chat/service/impl/CreateRoomServiceImpl.java
  src/main/java/com/ezel/voza/domain/chat/service/impl/FindAllChatServiceImpl.java
  src/main/java/com/ezel/voza/global/util/DateUtil.java
Labels: :one: Priority: High, :sparkler: Feature, :recycle: Refactoring

#119 Feat/user room refactoring
  src/main/java/com/ezel/voza/domain/chat/exception/NotAllowedFindChatException.java
  src/main/java/com/ezel/voza/domain/chat/exception/NotExistRoomUserException.java
  src/main/java/com/ezel/voza/domain/chat/service/RoomOutService.java
  src/main/java/com/ezel/voza/domain/chat/service/impl/FindAllChatServiceImpl.java
  src/main/java/com/ezel/voza/domain/chat/service/impl/RoomOutServiceImpl.java
  src/main/java/com/ezel/voza/domain/group/service/impl/OutGroupServiceImpl.java
  src/main/java/com/ezel/voza/global/error/ErrorCode.java
Labels: :one: Priority: High, :recycle: Refactoring

#121 Feat/calender hotfix
  src/main/java/com/ezel/voza/domain/calender/exception/CalenderAuthorMismatchException.java
  src/main/java/com/ezel/voza/domain/calender/exception/CalenderNotFoundException.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/DeleteCalenderServiceImpl.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/UpdateCalenderServiceImpl.java
  src/main/java/com/ezel/voza/global/util/CalenderUtil.java
Labels: :bug: Bug, :one: Priority: High, ⚡️Simple

#129 Feat/add vote response value
  src/main/java/com/ezel/voza/domain/vote/entity/Vote.java
  src/main/java/com/ezel/voza/domain/vote/entity/VoteOption.java
  src/main/java/com/ezel/voza/domain/vote/presentation/dto/request/CreateVoteRequest.java
  src/main/java/com/ezel/voza/domain/vote/presentation/dto/response/DetailVoteResponse.java
  src/main/java/com/ezel/voza/domain/vote/presentation/dto/response/VoteOptionResponse.java
  src/main/java/com/ezel/voza/domain/vote/presentation/dto/response/VoteResponse.java
  src/main/java/com/ezel/voza/domain/vote/service/impl/CreateVoteServiceImpl.java
  src/main/java/com/ezel/voza/domain/vote/service/impl/GetVoteDetailServiceImpl.java
  src/main/java/com/ezel/voza/domain/vote/service/impl/ListVoteServiceImpl.java
Labels: :bug: Bug, :one: Priority: High, :recycle: Refactoring

#130 Feat/report testing
  src/main/java/com/ezel/voza/VozaApplication.java
  src/main/java/com/ezel/voza/global/test/AuditingConfig.java
  src/test/java/com/ezel/voza/domain/report/ReportTest.java
Labels: 🧪Test, :one: Priority: High

#133 Feat/fix vote add count
  src/main/java/com/ezel/voza/domain/vote/entity/Vote.java
  src/main/java/com/ezel/voza/domain/vote/entity/VoteOption.java
  src/main/java/com/ezel/voza/domain/vote/presentation/VoteController.java
  src/main/java/com/ezel/voza/domain/vote/presentation/dto/request/AddCountRequest.java
  src/main/java/com/ezel/voza/domain/vote/repository/VoteOptionRepository.java
  src/main/java/com/ezel/voza/domain/vote/service/AddCountService.java
  src/main/java/com/ezel/voza/domain/vote/service/impl/AddCountServiceImpl.java
Labels: :one: Priority: High, :recycle: Refactoring

#134 Feat/user test
  src/main/java/com/ezel/voza/global/security/config/SecurityConfig.java
  src/test/java/com/ezel/voza/domain/user/AdminUserTest.java
  src/test/java/com/ezel/voza/domain/user/UserProfileTest.java
Labels: 🧪Test, :one: Priority: High

#136 Feat/board test
  src/test/java/com/ezel/voza/domain/board/BoardTest.java
Labels: 🧪Test, :one: Priority: High

#138 Feat/log monitoring
  build.gradle
  src/main/java/com/ezel/voza/global/config/WebConfiguration.java
  src/main/java/com/ezel/voza/global/filter/CustomServletFilter.java
  src/main/java/com/ezel/voza/global/interceptor/LoggingInterceptor.java
  src/main/resources/application.yml
Labels: :one: Priority: High, :sparkler: Feature

#141 Feat/hotfix calender
  src/main/java/com/ezel/voza/domain/calender/presentation/CalenderController.java
  src/main/java/com/ezel/voza/domain/calender/presentation/dto/request/GetDateRequest.java
  src/main/java/com/ezel/voza/domain/calender/service/CalenderDayListService.java
  src/main/java/com/ezel/voza/domain/calender/service/CalenderMonthListService.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/CalenderDayListServiceImpl.java
  src/main/java/com/ezel/voza/domain/calender/service/Impl/CalenderMonthListServiceImpl.java
Labels: :bug: Bug, :one: Priority: High, :recycle: Refactoring

#149 feat/add kickOutTime value
  src/main/java/com/ezel/voza/domain/member/entity/enums/KickOutTime.java
  src/main/java/com/ezel/voza/global/util/KickOutTimeUtil.java
Labels: :one: Priority: High, ⚡️Simple
